language: node_js
node_js:
   - "0.10"
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - bower cache clean
  - bower update
  - grunt prod
notifications:
  email: true